---
- name: Update apt cache
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: install keychain to support ssh agent
  become: true
  ansible.builtin.package:
    name: keychain
    state: "{{ base__package_state }}"
  when:
    - ansible_os_family != 'RedHat'

- name: install keychain on centos
  become: true
  ansible.builtin.yum:
    name:
      - "{{ _base__keychain_rpm }}"
      - libselinux-python
    state: "{{ base__package_state }}"
  when:
    - ansible_os_family == 'RedHat' and ansible_distribution_version | float <= 7
