---
- name: Optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Not maintained anymore
  ansible.builtin.fail:
    msg: "Sorry, this role is Archive. New Role available at https://galaxy.ansible.com/l3d/packages - https://github.com/roles-ansible/ansible_role_packages.git"
