---
- name: Print OS Infos
  debug:
    msg: |
      ansible_os_family = '{{ ansible_os_family }}'
      ansible_distribution = '{{ ansible_distribution }}'
      ansible_distribution_version = '{{ ansible_distribution_version }}'
      ansible_distribution_release = '{{ ansible_distribution_release }}'
      ansible_machine = '{{ ansible_machine }}'

      inventory_hostname = '{{ inventory_hostname }}'
      ansible_hostname = '{{ ansible_hostname }}'
      ansible_fqdn = '{{ ansible_fqdn }}'
