---
name: Ansible check debian:sid

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:sid
        uses: roles-ansible/check-ansible-debian-sid-action@master
        with:
          targets: "./"
