---
name: Ansible check ubuntu:bionic

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with ubuntu:bionic
        uses: roles-ansible/check-ansible-ubuntu-bionic-action@master
        with:
          targets: "./"
