---
name: Ansible check fedora:33

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with fedora:33
        uses: roles-ansible/check-ansible-fedora-33-action@master
        with:
          targets: "./"
