---
name: Ansible check debian:stable

# yamllint disable-line rule:truthy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  schedule:
    - cron: '23 6 * */1 *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:stable
        uses: roles-ansible/check-ansible-debian-stable-action@master
        with:
          targets: "./"
