---
name: Ansible check centos:centos7

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with ubuntu:centos7
        uses: roles-ansible/check-ansible-centos-centos7-action@master
        with:
          targets: "./"
