---
name: Ansible check debian:stretch

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible check with debian:stretch
        uses: roles-ansible/check-ansible-debian-stretch-action@master
        with:
          targets: "./"
