---
name: Ansible check debian:stable

# yamllint disable-line rule:truthy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v3

      - name: 'ansible check with debian:stable'
        uses: roles-ansible/check-ansible-debian-stable-action@master
        with:
          targets: "./"
